# Generated by Django 3.0 on 2020-07-07 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0002_auto_20200707_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='bd',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bboard.Bd'),
        ),
    ]
