# Generated by Django 3.0 on 2020-05-01 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20200430_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to='archive/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
