# Generated by Django 3.0 on 2020-07-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0003_auto_20200707_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(help_text='150x150px', upload_to='archives/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
