# Generated by Django 3.0 on 2020-05-02 16:06

import bboard.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20200501_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='bd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Bd', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='img',
            name='img',
            field=models.ImageField(upload_to=bboard.models.get_timestamp_path, verbose_name='Изображение'),
        ),
    ]
