# Generated by Django 3.0 on 2020-05-02 19:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0005_auto_20200502_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='img',
            name='bd',
        ),
        migrations.AddField(
            model_name='bd',
            name='img',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Img', verbose_name='Фото'),
        ),
    ]
