# Generated by Django 3.0 on 2020-05-06 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_auto_20200503_0055'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd',
            name='img',
        ),
        migrations.AddField(
            model_name='img',
            name='bd',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bboard.Bd', verbose_name='Фото'),
        ),
    ]
