# Generated by Django 3.0 on 2020-05-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0007_auto_20200506_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='bd',
            name='imgurl',
            field=models.CharField(max_length=200, null=True, verbose_name='Фото'),
        ),
    ]
