# Generated by Django 3.0 on 2020-05-08 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0008_bd_imgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bd',
            name='imgurl',
        ),
    ]
