# Generated by Django 3.0 on 2020-05-08 20:53

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0012_auto_20200509_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='photo',
            field=models.ImageField(null=True, upload_to=bboard.models.get_timestamp_path, verbose_name='фото'),
        ),
    ]
