# Generated by Django 3.0 on 2020-05-09 06:56

import bboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0013_auto_20200509_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='photo',
            field=models.ImageField(default='/static/bboard/1s-tovary_logo.bmp', upload_to=bboard.models.get_timestamp_path, verbose_name='фото'),
        ),
    ]
