# Generated by Django 3.0 on 2020-05-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0016_auto_20200512_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='photo',
            field=models.ImageField(upload_to='archives/%Y/%m/%d/username', verbose_name='фото'),
        ),
    ]
