# Generated by Django 3.0 on 2020-05-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0018_auto_20200512_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bd',
            name='photo',
            field=models.ImageField(upload_to='archives/%Y/%m/%d/', verbose_name='фото'),
        ),
    ]
